name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build plugins
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build plugins
        run: |
          mkdir dist
          for plugin in $(find . -type f -name manifest.json -exec dirname {} \; | cut -c3-); do
            node build.mjs "$plugin"
          done
      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v3
        if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch) # Only runs if this CI was not triggered by the default branch
        with:
          name: dist
          path: dist/*.{zip,json}

      - name: Checkout builds
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) # Only runs if this CI was triggered by the default branch
        uses: actions/checkout@master
        with:
          ref: 'builds'
          path: 'builds'

      - name: Push builds
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) # Only runs if this CI was triggered by the default branch
        run: |
          rm $GITHUB_WORKSPACE/builds/* || true # clean previous builds
          cp dist/*.{zip,json} $GITHUB_WORKSPACE/builds
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push --force
